LibraryManagementUI/Controllers/TransactionController.cs
using LibraryManagementCore.DTOs;
using LibraryManagementCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryManagementUI.Controllers
{
    [Route("[controller]")]
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly IBookService _bookService;
        private readonly IMemberService _memberService;
        public TransactionController(ITransactionService transactionService, IBookService bookService, IMemberService memberService)
        {
            _transactionService = transactionService;
            _bookService = bookService;
            _memberService = memberService;
        }
        [Route("GetAllTransaction")]
        public IActionResult GetAllTransaction()
        {
            var response = _transactionService.GetAllTransaction();
            return View(response);
        }
        [Route("AddTransaction")]
        [HttpGet]
        public IActionResult AddTransactions()
        {
            var response = new TransactionRequestDTO();
            //var books= _bookService.GetAllBooks();
            //var members = _memberService.GetAllMembers();
            var transaction = _transactionService.GetAllTransaction();
            var allBookId = transaction.Select(x => x.Books);
            var allMembers = transaction.Select(x => x.Members);
            ViewBag.Book = allBookId.Select(x => new SelectListItem
            {
                Value = x.BookId.ToString(), // dropdown value
                Text = x.Title               // dropdown display text
            }).ToList();
            ViewBag.Member = allMembers.Select(x => new SelectListItem
            {
                Value = x.MemoberId.ToString(),
                Text = x.Name
            }).ToList();
            return View(response);
        }
        [Route("AddTransaction")]
        [HttpPost]
        public IActionResult AddTransactions(TransactionRequestDTO request)
        {
            var response = _transactionService.AddNewTransaction(request);
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = "Transaction added successfully!";
                return RedirectToAction("GetAllTransaction");
            }
            else
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                TempData["ErrorMessage"] = "Failed to add Transaction!";
                return View(response);
            }
        }
    }
}

LibraryManagementUI/Views/Transaction/AddTransactions.cshtml
@{
    ViewData["Title"] = "Add New Transaction";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using LibraryManagementCore.DTOs
@model TransactionRequestDTO
@{
    TempData.Keep("SuccessMessage");
    TempData.Keep("ErrorMessage");
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<form asp-action="AddTransaction" asp-controller="Transaction" method="post">
    <label asp-for="BookId" class="form-control">Title</label>
    <select asp-for="@Model.BookId" asp-items="@ViewBag.Book"  class="form-control">
        <option value="@Model.BookId">Select Book</option>
        </select>
    <br />
    <select asp-for="@Model.MemberId" asp-items="@ViewBag.Member"  class="form-control">
        <option value="@Model.MemberId">Select Member</option>
    </select>
    <span asp-validation-for="@Model.MemberId" class="text-danger"></span>
    <br />
    <label asp-for="BorrowDate" class="form-control">BorrowDate</label>
    <input asp-for="@Model.BorrowDate" class="form-control" type="date" />
    <span asp-validation-for="@Model.BorrowDate" class="text-danger"></span>
    <br />
    <label asp-for="ReturnDate" class="form-control">ReturnDate</label>
    <input asp-for="@Model.ReturnDate" class="form-control" type="date" />
    <span asp-validation-for="@Model.ReturnDate" class="text-danger"></span>
    <br />
    <label asp-for="FineAmount" class="form-control">FineAmount</label>
    <input asp-for="@Model.FineAmount" class="form-control" />
    <span asp-validation-for="@Model.FineAmount" class="text-danger"></span>
    <br />
    <button class="btn btn-Primary" type="submit">Create</button>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js" integrity="sha512-KFHXdr2oObHKI9w4Hv1XPKc898mE4kgYx58oqsc/JqqdLMDI4YjOLzom+EMlW8HFUd0QfjfAvxSL6sEq/a42fQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

LibraryManagementUI/Views/Transaction/GetAllTransaction.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Transaction";
}
@using LibraryManagementCore.DTOs;
@model List<TransactionResponseDTO>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
<h1 class="text-center text-primary">Transaction</h1>
<a asp-controller="Transaction" asp-action="AddTransactions" class="btn btn-primary text-center mt-1">Add</a>
<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Member</th>
            <th>BorrowDate</th>
            <th>ReturnDate</th>
            <th>FineAmount</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.BookId</td>
                <td>@item.MemberId</td>
                <td>@item.BorrowDate</td>
                <td>@item.ReturnDate</td>
                <td>@item.FineAmount</td>
            </tr>
        }
    </tbody>
</table>