LibraryManagementUI/Controllers/BookController.cs
using LibraryManagementCore.DTOs;
using LibraryManagementCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementUI.Controllers
{
    [Route("[controller]")]
    public class BookController:Controller
    {
        private readonly IBookService bookService;
        public BookController(IBookService bookService)
        {
            this.bookService = bookService;
        }
        [Route("GetAllBooks")]
        [Route("/")]
        public IActionResult GetAllBooks()
        {
           List<BookResponseDTO> response= bookService.GetAllBooks();
            return View(response);

        }
        [Route("AddNewBooks")]
        [HttpGet]
        public IActionResult AddNewBook()
        {
            BookResponseDTO requestDTO =new BookResponseDTO();
            return View(requestDTO);

        }
        [Route("AddNewBooks")]
        [HttpPost]
        public IActionResult AddNewBook(BookRequestDTO requestDTO)
        {
            BookResponseDTO response = bookService.AddNewBook(requestDTO);
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = "Book added successfully!";
                return RedirectToAction("GetAllBooks");
            }
            else
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                TempData["ErrorMessage"] = "Failed to add book!";
                return View(response);
            }

        }
        [Route("UpdateBooks/{title}")]
        [HttpGet]
        public IActionResult UpdateBooks(string title)
        {
            BookResponseDTO requestDTO = bookService.FindBookByTitle(title);
            return View(requestDTO);

        }
        [Route("UpdateBooks/{title}")]
        [HttpPost]
        public IActionResult UpdateBooks(string title,BookRequestDTO requestDTO)
        {
            BookResponseDTO response = bookService.UpdateExistingBook(requestDTO.Title,requestDTO);
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = "Book Updated successfully!";
                return RedirectToAction("GetAllBooks");
            }
            else
            {
                var errors = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                TempData["ErrorMessage"] = "Failed to Update the book!";
                return View(response);
            }

        }
        [Route("RemoveBook/{title}")]
        [HttpGet]
        public IActionResult RemoveBooks(string title)
        {
            bool result = bookService.RemoveBook(title);
            if(result)
            {
                TempData["SuccessMessage"] = "Book removed successfully!";
                return RedirectToAction("GetAllBooks");
            }
            else
            {
                TempData["ErrorMessage"] = "Failed to remove the book!";
                return BadRequest("Book not found or could not be removed.");
            }
               

        }
    }
}

LibraryManagementUI/Controllers/MemberController.cs
using Azure.Core;
using LibraryManagementCore.DTOs;
using LibraryManagementCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementUI.Controllers
{
    [Route("[controller]")]
    public class MemberController : Controller
    {
        private readonly IMemberService memberService;
        public MemberController(IMemberService memberService)
        {
            this.memberService = memberService;
        }
        [Route("getAllMembers")]
        public IActionResult GetAllMembers()
        {
            var response = memberService.GetAllMembers();
            return View(response);
        }
        [Route("AddNewMembers")]
        [HttpGet]
        public IActionResult AddNewMembers()
        {
            MemberResponseDTO request = new MemberResponseDTO();
            return View(request);
        }
        [Route("AddNewMembers")]
        [HttpPost]
        public IActionResult AddNewMembers(MemberRequestDTO request)
        {
            var response = memberService.AddNewMember(request);
            if (ModelState.IsValid)
            {
                TempData["SuccessMessage"] = "Member added successfully!";
                return RedirectToAction("GetAllMembers");
            }
            else
            {
                var error = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                TempData["ErrorMessage"] = "Failed to add Member!";
                return View(response);
            }
        }
        [Route("UpdateMembers/{name}")]
        [HttpGet]
        public IActionResult UpdateMembers(string name)
        {
            var member = memberService.FindMemberByName(name);
            return View(member);
        }
        [Route("UpdateMembers/{name}")]
        [HttpPost]
        public IActionResult UpdateMembers(string name,MemberRequestDTO response)
        {
            if (ModelState.IsValid)
            {
                memberService.UpdateExistingMember(name, response);
                TempData["SuccessMessage"] = "Member Updated successfully!";
                return RedirectToAction("GetAllMembers");
            }
            else
            {
                var error = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage);
                TempData["ErrorMessage"] = "Failed to Update the Member!";
                return View(response);
            }
        }
        [Route("RemoveMember/{name}")]
        [HttpGet]
        public IActionResult RemoveMember(string name)
        {
            var member = memberService.RemoveMember(name);
            if(member)
                {
                TempData["SuccessMessage"] = "Member removed successfully!";
                return RedirectToAction("GetAllMembers");
            }
            else
            {
                TempData["ErrorMessage"] = "Failed to remove the Member!";
                return BadRequest("Member not found or could not be removed.");
            }
        }
    }
}

LibraryManagementUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <title>@ViewBag.Title</title>

</head>
<body class="bg-dark-subtle">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Library Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a asp-controller="Book" asp-action="GetAllBooks" class="btn btn-primary text-center mt-1">Books</a>
                    <a asp-controller="Member" asp-action="GetAllMembers" class="btn btn-primary text-center mt-1">Members</a>
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </div>
            </div>
        </div>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
</html>

LibraryManagementUI/Views/Shared/_sweetAlertPartialView.cshtml
<script>
    document.addEventListener("DOMContentLoaded", function () {
        @* Success Alert *@
        @if (Model[0] != null)
        {
                        <text>
                            Swal.fire({
                                icon: 'success',
                                title: 'Success',
                                    text: '@Model[0]',
                                timer: 3000,
                                showConfirmButton: false
                            });
                        </text>
        }

        @* Error Alert *@
        @if (Model[1] != null)
        {
                        <text>
                            Swal.fire({
                                icon: 'error',
                                title: 'Error',
                                    text: '@Model[1]]'
                            });
                        </text>
        }
    });
</script>